-- MySQL Script generated by MySQL Workbench
-- Sat Jun 25 23:11:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema awkicare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema awkicare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `awkicare` DEFAULT CHARACTER SET utf8 ;
USE `awkicare` ;

-- -----------------------------------------------------
-- Table `awkicare`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awkicare`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(12) NULL,
  `password` VARCHAR(45) NULL,
  `nombres` VARCHAR(60) NULL,
  `apellidos` VARCHAR(60) NULL,
  `dni` INT(8) NULL,
  `genero` VARCHAR(45) NULL,
  `direccion` VARCHAR(120) NULL,
  `ubigeo` INT(6) ZEROFILL NULL,
  `correo` VARCHAR(60) NULL,
  `telefono` VARCHAR(15) NULL,
  `nacimiento` DATE NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idusuarios`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) ,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awkicare`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awkicare`.`pacientes` (
  `idpacientes` INT NOT NULL AUTO_INCREMENT,
  `idusuarios` INT NOT NULL,
  `nombres` VARCHAR(60) NULL,
  `apellidos` VARCHAR(60) NULL,
  `dni` INT(8) NULL,
  `genero` VARCHAR(45) NULL,
  `direccion` VARCHAR(120) NULL,
  `ubigeo` INT(6) ZEROFILL NULL,
  `correo` VARCHAR(60) NULL,
  `telefono` VARCHAR(15) NULL,
  `nacimiento` DATE NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idpacientes`, `idusuarios`),
  INDEX `fk_pacientes_usuarios1_idx` (`idusuarios` ASC) ,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) ,
  CONSTRAINT `fk_pacientes_usuarios1`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `awkicare`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awkicare`.`enfermeros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awkicare`.`enfermeros` (
  `idenfermeros` INT NOT NULL AUTO_INCREMENT,
  `idusuarios` INT NOT NULL,
  `nombres` VARCHAR(60) NULL,
  `apellidos` VARCHAR(60) NULL,
  `dni` INT(8) NULL,
  `genero` VARCHAR(45) NULL,
  `direccion` VARCHAR(120) NULL,
  `ubigeo` INT(6) NULL,
  `correo` VARCHAR(60) NULL,
  `telefono` VARCHAR(15) NULL,
  `nacimiento` DATE NULL,
  `codigo_cep` VARCHAR(15) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idenfermeros`, `idusuarios`),
  INDEX `fk_enfermeros_usuarios1_idx` (`idusuarios` ASC) ,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) ,
  UNIQUE INDEX `codigo_cep_UNIQUE` (`codigo_cep` ASC) ,
  CONSTRAINT `fk_enfermeros_usuarios1`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `awkicare`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awkicare`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awkicare`.`servicios` (
  `idservicios` INT NOT NULL AUTO_INCREMENT,
  `idusuarios` INT NOT NULL,
  `nombre_servicio` VARCHAR(45) NULL,
  `descripcion` TEXT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idservicios`, `idusuarios`),
  INDEX `fk_servicios_usuarios1_idx` (`idusuarios` ASC) ,
  UNIQUE INDEX `nombre_servicio_UNIQUE` (`nombre_servicio` ASC) ,
  CONSTRAINT `fk_servicios_usuarios1`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `awkicare`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awkicare`.`servicios_enfermeros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awkicare`.`servicios_enfermeros` (
  `idservicios_enfermeros` INT NOT NULL AUTO_INCREMENT,
  `idenfermeros` INT NOT NULL,
  `idusuarios` INT NOT NULL,
  `servicios_idservicios` INT NOT NULL,
  `servicios_idusuarios` INT NOT NULL,
  `monto` DOUBLE NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idservicios_enfermeros`, `idenfermeros`, `idusuarios`, `servicios_idservicios`, `servicios_idusuarios`),
  INDEX `fk_servicios_enfermeros_enfermeros1_idx` (`idenfermeros` ASC, `idusuarios` ASC) ,
  INDEX `fk_servicios_enfermeros_servicios1_idx` (`servicios_idservicios` ASC, `servicios_idusuarios` ASC) ,
  CONSTRAINT `fk_servicios_enfermeros_enfermeros1`
    FOREIGN KEY (`idenfermeros` , `idusuarios`)
    REFERENCES `awkicare`.`enfermeros` (`idenfermeros` , `idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicios_enfermeros_servicios1`
    FOREIGN KEY (`servicios_idservicios` , `servicios_idusuarios`)
    REFERENCES `awkicare`.`servicios` (`idservicios` , `idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awkicare`.`solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awkicare`.`solicitudes` (
  `idsolicitudes` INT NOT NULL AUTO_INCREMENT,
  `numero_solicitud` VARCHAR(45) NULL,
  `fecha_solicitud` DATE NULL,
  `observacion` TEXT NULL,
  `estado` VARCHAR(45) NULL,
  `idpacientes` INT NOT NULL,
  `idenfermeros` INT NOT NULL,
  `idservicios` INT NOT NULL,
  `servicios_idservicios` INT NOT NULL,
  `idservicios_enfermeros` INT NOT NULL,
  `fecha_registro` DATETIME NULL,
  PRIMARY KEY (`idsolicitudes`, `idpacientes`, `idenfermeros`, `idservicios`, `servicios_idservicios`, `idservicios_enfermeros`),
  INDEX `fk_solicitudes_pacientes1_idx` (`idpacientes` ASC) ,
  INDEX `fk_solicitudes_servicios_enfermeros1_idx` (`idservicios_enfermeros` ASC) ,
  CONSTRAINT `fk_solicitudes_pacientes1`
    FOREIGN KEY (`idpacientes`)
    REFERENCES `awkicare`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudes_servicios_enfermeros1`
    FOREIGN KEY (`idservicios_enfermeros`)
    REFERENCES `awkicare`.`servicios_enfermeros` (`idservicios_enfermeros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awkicare`.`solicitudes_atendidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awkicare`.`solicitudes_atendidas` (
  `idsolicitudes_atendidas` INT NOT NULL AUTO_INCREMENT,
  `idenfermeros` INT NOT NULL,
  `fecha_atencion` DATE NULL,
  `estado` INT NULL,
  `idsolicitudes` INT NOT NULL,
  `idservicios` INT NOT NULL,
  `idpacientes` INT NOT NULL,
  PRIMARY KEY (`idsolicitudes_atendidas`, `idenfermeros`, `idsolicitudes`, `idservicios`, `idpacientes`),
  INDEX `fk_solicitudes_atendidas_solicitudes1_idx` (`idsolicitudes` ASC, `idservicios` ASC, `idpacientes` ASC) ,
  CONSTRAINT `fk_solicitudes_atendidas_solicitudes1`
    FOREIGN KEY (`idsolicitudes` , `idpacientes`)
    REFERENCES `awkicare`.`solicitudes` (`idsolicitudes` , `idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awkicare`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awkicare`.`pagos` (
  `idpagos` INT NOT NULL AUTO_INCREMENT,
  `fecha_pago` DATETIME NULL,
  `idsolicitudes` INT NOT NULL,
  `monto` DOUBLE NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idpagos`, `idsolicitudes`),
  INDEX `fk_pagos_solicitudes1_idx` (`idsolicitudes` ASC) ,
  CONSTRAINT `fk_pagos_solicitudes1`
    FOREIGN KEY (`idsolicitudes`)
    REFERENCES `awkicare`.`solicitudes` (`idsolicitudes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awkicare`.`comisiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awkicare`.`comisiones` (
  `idcomisiones` INT NOT NULL AUTO_INCREMENT,
  `idpagos` INT NOT NULL,
  `fecha_cobro` DATE NULL,
  `monto_comision` DOUBLE NULL,
  `monto_utilidad` DOUBLE NULL,
  `idenfermeros` INT NOT NULL,
  `idusuarios` INT NOT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idcomisiones`, `idpagos`, `idenfermeros`, `idusuarios`),
  INDEX `fk_comisiones_pagos1_idx` (`idpagos` ASC) ,
  INDEX `fk_comisiones_enfermeros1_idx` (`idenfermeros` ASC, `idusuarios` ASC) ,
  CONSTRAINT `fk_comisiones_pagos1`
    FOREIGN KEY (`idpagos`)
    REFERENCES `awkicare`.`pagos` (`idpagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comisiones_enfermeros1`
    FOREIGN KEY (`idenfermeros` , `idusuarios`)
    REFERENCES `awkicare`.`enfermeros` (`idenfermeros` , `idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awkicare`.`calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awkicare`.`calificaciones` (
  `idcalificaciones` INT NOT NULL AUTO_INCREMENT,
  `idusuarios` INT NOT NULL,
  `idsolicitudes_atendidas` INT NOT NULL,
  `calificacion_enfermero` INT(1) NULL,
  `calificacion_servicio` INT(1) NULL,
  `comentario` TEXT NULL,
  PRIMARY KEY (`idcalificaciones`, `idusuarios`, `idsolicitudes_atendidas`),
  INDEX `fk_calificaciones_enfermeros1_idx` (`idusuarios` ASC) ,
  INDEX `fk_calificaciones_solicitudes_atendidas1_idx` (`idsolicitudes_atendidas` ASC) ,
  CONSTRAINT `fk_calificaciones_enfermeros1`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `awkicare`.`enfermeros` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificaciones_solicitudes_atendidas1`
    FOREIGN KEY (`idsolicitudes_atendidas`)
    REFERENCES `awkicare`.`solicitudes_atendidas` (`idsolicitudes_atendidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
